// Code generated by "stringer -type=Priority"; DO NOT EDIT.

package transmission

import "fmt"

const _Priority_name = "LowNormalHigh"

var _Priority_index = [...]uint8{0, 3, 9, 13}

func (i Priority) String() string {
	i -= -1
	if i < 0 || i >= Priority(len(_Priority_index)-1) {
		return fmt.Sprintf("Priority(%d)", i+-1)
	}
	return _Priority_name[_Priority_index[i]:_Priority_index[i+1]]
}
